<?php

echo "<h1>Recycle Bin</h1>";

echo PHP_EOL;

echo PHP_EOL;

// echo $this->tag->linkTo([
//     'taskmanage',
//     'Manage',
//     'class' => 'btn btn-primary'
// ]);

// echo "   ";

echo $this->tag->linkTo([
    'index',
    'Main Page',
    'class' => 'btn btn-primary'
]);

if ($tasks->count() > 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
            <?php $counter = 0; ?>
        <tr>
            <th>#</th>
            <th>Task</th>
        </tr>
        </thead>
        
        <body>
        <?php foreach ($tasks as $task) {
                if ($task->status == 1) { 
                    $counter++; ?>
            <tr>
                <td><?php echo $task->id; ?></td>
                <td><?php echo $task->task; ?></td>
                <td><?php   echo $this->tag->form("index/restore/" .$task->id);
                            echo $this->tag->submitButton("restore"); ?></form>
                    <?php   echo $this->tag->form("index/delete/" .$task->id);
                            echo $this->tag->submitButton("delete"); ?></form>            
            </tr>
        <?php }} ?>
        <tfoot>
            <tr>
                <td colspan="3">Tasks to do: <?php echo $counter; ?></td>
            </tr>
        </tfoot>
        </tbody>
    </table>
    <?php
}
