<h1>Recycle Bin</h1>
<?php


echo PHP_EOL;

echo PHP_EOL;


echo $this->tag->linkTo([
    'index',
    'Main Page',
    'class' => 'btn btn-primary btn-lg'
]);

    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
            <?php $counter = 0; ?>
        <tr>
            <th>#</th>
            <th>Task</th>
            <th></th>
        </tr>
        </thead>
        
        <body>
        <?php foreach ($tasks as $task) {
                if ($task->status == 1) { 
                    $counter++; 
        ?>
            <tr>
                <td><?php echo $task->id; ?></td>
                <td><?php echo $task->task; ?></td>
                <td><?php echo $this->tag->linkTo([
                                'taskmanage/restore/' . $task->id,
                                'Restore',
                                'class' => 'btn btn-secondary'
                            ]);
                            echo " ";
                            echo $this->tag->linkTo([
                                'taskmanage/delete/' . $task->id,
                                'Delete',
                                'class' => 'btn btn-secondary'
                            ]);
                            ?>        
            </tr>
        <?php }} ?>
        <tfoot>
            <tr>
                <td colspan="3">Tasks to do: <?php echo $counter; ?></td>
            </tr>
        </tfoot>
        </tbody>
    </table>
    <?php
    
