<h2>Add/Remove Tasks</h2>

<?php echo $this->tag->form("taskmanage/add"); ?>

    <p>
        <label for="name">Task</label>
        <?php echo $this->tag->textField("task"); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton("Add"); ?>
    </p>

</form>

<?php echo $this->tag->form("taskmanage/recycle"); ?>

    <p>
        <label for="id">Task</label>
        <?php echo $this->tag->textField("id"); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton("recycle"); ?>
    </p>

</form>

<?php echo $this->tag->form("taskmanage/update"); ?>

    <p>
        <label for="id">Task Id</label>
        <?php echo $this->tag->textField("id"); ?>
        <label for="id">Task</label>
        <?php echo $this->tag->textField("task"); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton("update"); ?>
    </p>

</form>

<?php echo $this->tag->linkTo([
                    'index',
                    'Main Page',
                ]); ?>