<h2>Edit Task</h2>


    <?php echo $this->tag->form("index/update/" .$task->id); ?>

        <p>

            <label for="task">Task: </label>
            <?php echo $this->tag->textField(["value" => $task->task, "id" => $task->id, "name" => "task"]); ?>
        </p>

        <p>
            <?php echo $this->tag->submitButton([
                "value" => "Update",
                "class" => "btn btn-secondary"
            
            ]) ?>
        </p>

    </form>
</html>

<?php echo $this->tag->linkTo([
                    'index',
                    '<< Back',
                ]); ?>
                