<h2>Add New Task</h2>

<?php echo $this->tag->form("taskmanage/add"); ?>

    <p>
        <label for="name">Task: </label>
        <?php echo $this->tag->textField("task"); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton([
            "value" => "Add",
            "class" => "btn btn-secondary"
                                            
    
    ]); ?>
    </p>

</form>

<?php echo $this->tag->linkTo([
                    'index',
                    '<< Back',
                ]); ?>