<?php

echo "<h1>Simple To-do List</h1>";

echo PHP_EOL;

echo PHP_EOL;

echo $this->tag->linkTo([
    'taskmanage',
    'Manage',
    'class' => 'btn btn-primary'
]);

if ($tasks->count() > 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>Task</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Tasks to do<?php echo $tasks->count(); ?></td>
        </tr>
        </tfoot>
        <body>
        <?php foreach ($tasks as $task) { ?>
            <tr>
                <td><?php echo $task->id; ?></td>
                <td><?php echo $task->task; ?></td>
                <td><?php echo $this->tag->submitButton("remove"); ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}
