<?php

echo "<h1>Simple To-do List</h1>";

echo PHP_EOL;

echo PHP_EOL;

echo $this->tag->linkTo([
    'taskmanage/taskadd',
    'Add New',
    'class' => 'btn btn-primary'
]);

echo "   ";

echo $this->tag->linkTo([
    'taskmanage',
    'Manage',
    'class' => 'btn btn-primary'
]);

echo "   ";

echo $this->tag->linkTo([
    'recycle',
    'Recycle Bin',
    'class' => 'btn btn-primary'
]);

if ($tasks->count() > 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
            <?php $counter = 0; ?>
        <tr>
            <th>#</th>
            <th>Task</th>
            <th></th>
        </tr>
        </thead>
        
        <body>
        <?php foreach ($tasks as $task) {
                if ($task->status == 0) { 
                    $counter++; 
                    ?>
            <tr>
                <td><?php   echo $task->id;?></td>
                <td><?php   echo $task->task; ?></td>
                <td><?php   /*echo $this->tag->form("index/recycle/" . $task->id); 
                            echo $this->tag->submitButton("recycle"); ?></form>*/  
                    // echo $this->tag->form("taskmanage/taskedit/" . $task->id); 
                            // echo $this->tag->submitButton("edit");
                            echo $this->tag->linkTo([
                                'index/recycle/' . $task->id,
                                'Recycle',
                                'class' => 'btn btn-primary'
                            ]);
                            echo " ";
                            echo $this->tag->linkTo([
                                'taskmanage/taskedit/' . $task->id,
                                'Edit',
                                'class' => 'btn btn-primary'
                            ]);
                            ?>     
                            

            </tr>
        <?php }} ?>
        <tfoot>
        <tr>
            <td colspan="3">Tasks to do: <?php echo $counter; ?></td>
        </tr>
        </tfoot>
        </tbody>
    </table>
    <?php
}
?>

